/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bfgtbdwywhmmoouyyxda"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZ3RiZHd5d2htbW9vdXl5eGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjUyNjEsImV4cCI6MjA3NDc0MTI2MX0.LvXOoe5NAIjoVi-O2IcI2lkniif7N-GcnmQB9rPWIeI"